name: "Asteroids Linux Build"
on: workflow_dispatch

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      # TODO: setup-sdl + sdl_ttf + sdl_mixer
      - name: install_dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
          sudo apt-get install libsdl2-image1.2-dev
          sudo apt-get install libsdl2-ttf2.0-dev
          ls

      - uses: actions/checkout@master

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          source-dir: AsteroidsSDL/src
          build-dir: out
      # TODO: build output zip + release
