name: "Asteroids Linux Build"
on: workflow_dispatch

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      # TODO: setup-sdl + sdl_ttf + sdl_mixer
      - name: Install Dependencies
        id: dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt install zip
          sudo apt-get install libsdl2-dev
          sudo apt-get install libsdl2-image-dev
          sudo apt-get install libsdl2-ttf-dev

      #      - name: Find Libraries
      #        id: find_libraries
      #        run: |
      #          echo ::set-env name=SDL_LOC::$(find /usr/lib -name SDL2)

      - uses: actions/checkout@master

      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          source-dir: AsteroidsSDL/src
          build-dir: out

      - name: Zip result
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
#          cp -v ${{env.SDL_LOC }} AsteroidsSDL/out
           zip AsteroidsLinux.zip AsteroidsSDL/out 

      # TODO: build output zip + release
      - name: Release Output
        id: create_release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: AsteroidsSDL/out/AsteroidsLinux.zip
          asset_name: AsteroidsLinux
          tag: ${{ github.ref }}
          overwrite: true
          body: "Build for linux"
