name: "Asteroids Linux Build"
on: workflow_dispatch

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: BrettDong/setup-sdl2-frameworks@main
        with:
          sdl2: latest
          sdl2-ttf: latest
          sdl2-image: 2.6.3
          sdl2-mixer: none
          sdl2-net: none

      - name: "linux setup + build"
        run: |
          cmake -s . -B build
          cmake --build build --verbose
