name: "Asteroids Linux Build"
on: workflow_dispatch

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: install_dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Configure and Build Project
        uses: threeal/cmake-action@main
        with:
          source-dir: AsteroidsSDL/src
          build-dir: out
