name: "Asteroids Cross-Platform Build"
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.previoustag.outputs.tag }}
      release_url: ${{steps.create_release.outputs.upload_url}}
      version_number: ${{steps.versionnum.outputs.version}}
      semantic_version: ${{steps.versionvnum.outputs.v_version}}
    steps:
      - uses: actions/checkout@master
      - name: Get Version Number
        id: versionnum
        run: |
          echo "version=$(cat AsteroidsSDL/src/config.txt | head -2 | tail -1)" >> $GITHUB_OUTPUT

      - name: Concatenate 'v'
        id: versionvnum
        run: |
          echo "v_version=$(printf "v%s" ${{ steps.versionnum.outputs.version }})" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versionnum.outputs.version }}
          release_name: ${{ steps.versionvnum.outputs.v_version}}
          draft: false
          prerelease: false

  build_windows_64:
    runs-on: windows-latest
    needs: create_release
    steps:
      - uses: actions/checkout@master

      - name: Dependency | Fetch SDL
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "libsdl-org/SDL"
          tag: "release-2.30.3"
          fileName: "SDL2-devel-2.30.3-VC.zip"

      - name: Dependency | Fetch SDL_ttf
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "libsdl-org/SDL_ttf"
          version: "tags/release-2.22.0"
          file: "SDL2_ttf-devel-2.22.0-VC.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependency | Fetch SDL_image
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "libsdl-org/SDL_image"
          version: "tags/release-2.8.2"
          file: "SDL2_image-devel-2.8.2-VC.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependency | Unzip SDL Libs
        run: |
          mkdir SDL2
          mkdir SDL2_ttf
          mkdir SDL2_image
          powershell -command "Expand-Archive -Force './SDL2-devel-2.30.3-VC.zip' 'SDL2'"
          powershell -command "Expand-Archive -Force './SDL2_image-devel-2.8.2-VC.zip' 'SDL2_image'"
          powershell -command "Expand-Archive -Force './SDL2_ttf-devel-2.22.0-VC.zip' 'SDL2_ttf'"
          chcp 65001 
          echo ("SDL2DIR=${{ github.workspace }}/SDL2/SDL2-2.30.3") >> $env:GITHUB_ENV
          echo ("SDL2IMAGEDIR=${{ github.workspace }}/SDL2_image/SDL2_image-2.8.2") >> $env:GITHUB_ENV
          echo ("SDL2TTFDIR=${{ github.workspace }}/SDL2_ttf/SDL2_ttf-2.22.0") >> $env:GITHUB_ENV

      - name: x64 | Configure and Build Project
        run: |
          cd AsteroidsSDL\src
          cmake . -G "Visual Studio 17 2022" -A x64 -DCMAKE_CONFIGURATION_TYPES="Release" -DSDL2_DIR=${{env.SDL2DIR}} -DSDL2IMAGEDIR=${{env.SDL2IMAGEDIR}} -DSDL2TTFLIBRARY=${{env.SDL2TTFDIR}} 
          cmake --build . --config Release

      - name: x64 | Run CPack
        run: |
          cd AsteroidsSDL\src
          cpack -G "NSIS"
          Get-ChildItem -Recurse

      - name: Upload Win64 Installer
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_url }} 
          asset_path: ./AsteroidsSDL/src/packages/AsteroidsSDL-${{ needs.create_release.outputs.version_number }}-win64.exe
          asset_name: AsteroidsSDL-${{ needs.create_release.outputs.version_number }}-win64.exe
          asset_content_type: application/vnd.microsoft.portable-executable

  build_windows_32:
    runs-on: windows-latest
    needs: create_release
    steps:
      - uses: actions/checkout@master

      - name: Dependency | Fetch SDL
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "libsdl-org/SDL"
          tag: "release-2.30.3"
          fileName: "SDL2-devel-2.30.3-VC.zip"

      - name: Dependency | Fetch SDL_ttf
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "libsdl-org/SDL_ttf"
          version: "tags/release-2.22.0"
          file: "SDL2_ttf-devel-2.22.0-VC.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependency | Fetch SDL_image
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "libsdl-org/SDL_image"
          version: "tags/release-2.8.2"
          file: "SDL2_image-devel-2.8.2-VC.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dependency | Unzip SDL Libs
        run: |
          mkdir SDL2
          mkdir SDL2_ttf
          mkdir SDL2_image
          powershell -command "Expand-Archive -Force './SDL2-devel-2.30.3-VC.zip' 'SDL2'"
          powershell -command "Expand-Archive -Force './SDL2_image-devel-2.8.2-VC.zip' 'SDL2_image'"
          powershell -command "Expand-Archive -Force './SDL2_ttf-devel-2.22.0-VC.zip' 'SDL2_ttf'"
          chcp 65001 
          echo ("SDL2DIR=${{ github.workspace }}/SDL2/SDL2-2.30.3") >> $env:GITHUB_ENV
          echo ("SDL2IMAGEDIR=${{ github.workspace }}/SDL2_image/SDL2_image-2.8.2") >> $env:GITHUB_ENV
          echo ("SDL2TTFDIR=${{ github.workspace }}/SDL2_ttf/SDL2_ttf-2.22.0") >> $env:GITHUB_ENV

      - name: x86 | Configure and Build Project
        run: |
          cd AsteroidsSDL\src
          cmake . -G "Visual Studio 17 2022" -A x86 -DCMAKE_CONFIGURATION_TYPES="Release" -DSDL2_DIR=${{env.SDL2DIR}} -DSDL2IMAGEDIR=${{env.SDL2IMAGEDIR}} -DSDL2TTFLIBRARY=${{env.SDL2TTFDIR}} 
          cmake --build . --config Release

      - name: x86 | Run CPack
        run: |
          cd AsteroidsSDL\src
          cpack -G "NSIS"
          Get-ChildItem -Recurse

      - name: Upload Win32 Installer
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_url }} 
          asset_path: ./AsteroidsSDL/src/packages/AsteroidsSDL-${{ needs.create_release.outputs.version_number }}-win32.exe

  # TODO: Appimage and flatpak
  build_linux:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Install Dependencies
        id: dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt install zip
          sudo apt-get install libsdl2-dev
          sudo apt-get install libsdl2-image-dev
          sudo apt-get install libsdl2-ttf-dev

      - uses: actions/checkout@master

      - name: linux | Configure and Build Project
        run: |
          cd AsteroidsSDL/src
          cmake . -DCMAKE_CONFIGURATION_TYPES="Release" 
          cmake --build . --config Release

      - name: linux | Run CPack
        run: |
          cd AsteroidsSDL/src
          cpack 
          cd ../../
          tree .

      - name: Upload DragNDrop Installer
        id: linux_deb_upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_url }} 
          asset_path: ./AsteroidsSDL/src/Packaging/AsteroidsSDL-${{ needs.create_release.outputs.version_number }}-linux.dpkg
          asset_name: AsteroidsSDL-${{ needs.create_release.outputs.version_number }}-linux.dpkg
          asset_content_type: application/vnd.apple.installer+xml

  build_macos:
    runs-on: macos-latest
    needs: create_release
    steps:
      - name: Install Dependencies
        id: dependencies
        run: |
          brew install sdl2
          brew install sdl2_image
          brew install sdl2_ttf
          brew install tree

      - uses: actions/checkout@master

      - name: macOS | Configure and Build Project
        run: |
          cd AsteroidsSDL/src
          cmake . -DCMAKE_CONFIGURATION_TYPES="Release" 
          cmake --build . --config Release

      - name: macOS | Run CPack
        run: |
          cd AsteroidsSDL/src
          cpack 
          cd ../../
          tree .

      - name: Upload DragNDrop Installer
        id: macos_dmg_upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_url }} 
          asset_path: ./AsteroidsSDL/src/Packaging/AsteroidsSDL-${{ needs.create_release.outputs.version_number }}-macOS.dmg
          asset_name: AsteroidsSDL-${{ needs.create_release.outputs.version_number }}-macOS.dmg
          asset_content_type: application/vnd.apple.installer+xml

      - name: Upload productbuild Installer
        id: macos_pkg_upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_url }} 
          asset_path: ./AsteroidsSDL/src/Packaging/AsteroidsSDL-${{ needs.create_release.outputs.version_number }}-macOS.pkg
          asset_name: AsteroidsSDL-${{ needs.create_release.outputs.version_number }}-macOS.pkg
          asset_content_type: application/vnd.apple.installer+xml
