name: Asteroids Linux Build
on: workflow_dispatch
jobs:
  build_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working_directory: ./scripts
    steps:
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 2-latest
          version-sdl-image: 2-latest
      - name: "linux setup + build"
        run: |
          make
